version: 2

updates:
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    groups:
      web-security-and-maintenance:
        patterns:
          - "*"
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: pip
    directory: /apps/api
    schedule:
      interval: weekly
    groups:
      api-security-and-maintenance:
        patterns:
          - "*"
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
