import { expect, Page, test } from '@playwright/test'
import { setupApiMocks } from './fixtures/api-mocks'

async function gotoAppPage(page: Page, path: string) {
  await page.goto('/login', { waitUntil: 'domcontentloaded' })
  await page.evaluate(() => {
    localStorage.setItem('auth_token', 'mock-jwt-token-1234567890abcdef')
  })
  await page.goto(path, { waitUntil: 'domcontentloaded' })
}

test.describe('full document delivery workbench', () => {
  test.beforeEach(async ({ page }) => {
    await setupApiMocks(page)
  })

  test('shows the full project document delivery chain and readiness', async ({ page }) => {
    await gotoAppPage(page, '/projects/project-e2e-001/documents')

    await expect(page.getByTestId('project-document-workbench-heading')).toBeVisible({ timeout: 8000 })
    await expect(page.getByTestId('document-workflow-lanes')).toContainText('编写')
    await expect(page.getByTestId('document-quality-gates')).toContainText('质量门禁')
    await expect(page.getByTestId('document-control-matrix')).toBeVisible()
    await expect(page.getByTestId('document-control-matrix')).toContainText('交付控制矩阵')
    await expect(page.getByTestId('document-control-matrix')).toContainText('开始编写')
    await expect(page.getByTestId('document-source-coverage')).toBeVisible()
    await expect(page.getByTestId('document-source-coverage')).toContainText('资料可用')
    await expect(page.getByTestId('document-export-package')).toContainText('交付包')
    await expect(page.getByTestId('document-collaboration-review-export-linkage')).toBeVisible()
    await expect(page.getByTestId('document-collaboration-review-export-linkage')).toContainText('评审状态')
    await expect(page.getByTestId('document-collaboration-review-export-linkage')).toContainText('责任人/评审人')
    await expect(page.getByTestId('document-collaboration-review-export-linkage')).toContainText('交付包准备度')
    await expect(page.getByTestId('document-collaboration-review-export-linkage')).toContainText('下一步动作')
    await expect(page.getByTestId('document-collaboration-review-export-linkage')).toContainText('处理文档评审')
    await expect(page.getByTestId('document-collaboration-review-export-linkage')).toContainText('缺少 5 类核心交付文档')
    await expect(page.getByTestId('package-manifest-list')).toBeVisible()
    await expect(page.getByTestId('package-manifest-list')).toContainText('用户需求规格说明书')
    await expect(page.getByTestId('document-traceability-actions')).toBeVisible()
    await expect(page.getByTestId('document-traceability-actions').locator('a')).toHaveCount(2)
    await expect(page.getByTestId('document-collaboration-actions')).toBeVisible()
    await expect(page.getByTestId('document-collaboration-actions')).toContainText('继续对话式编写')
    await expect(page.getByTestId('document-collaboration-summary')).toContainText('协同状态')
    await expect(page.getByTestId('template-coverage-brd')).toBeVisible()
    await expect(page.getByTestId('delivery-chain-urs')).toBeVisible()
    await expect(page.getByTestId('delivery-chain-brd')).toBeVisible()
    await expect(page.getByTestId('delivery-chain-prd')).toBeVisible()
    await expect(page.getByTestId('delivery-chain-user_story')).toBeVisible()
    await expect(page.getByTestId('delivery-chain-detailed_design')).toBeVisible()
    await expect(page.getByTestId('delivery-chain-interface')).toBeVisible()
    await expect(page.getByTestId('delivery-chain-data_dictionary')).toBeVisible()
    await expect(page.getByTestId('delivery-chain-test_case')).toBeVisible()
    await expect(page.getByTestId('active-generation-sessions')).toContainText('PRD')
    await expect(page.locator('body')).toContainText('导出')

    await page.getByTestId('create-project-package-action').click()
    await expect(page.locator('body')).toContainText('交付包任务已创建', { timeout: 8000 })
  })

  test('shows document detail delivery readiness and lifecycle actions', async ({ page }) => {
    await gotoAppPage(page, '/projects/project-e2e-001/documents/doc-e2e-001')

    await expect(page.getByTestId('document-delivery-readiness')).toBeVisible({ timeout: 8000 })
    await expect(page.getByTestId('document-delivery-readiness')).toContainText('交付证据')
    await expect(page.getByTestId('document-delivery-review-panel')).toBeVisible()
    await expect(page.getByTestId('document-delivery-review-panel')).toContainText('交付/评审作战面板')
    await expect(page.getByTestId('document-delivery-review-panel')).toContainText('生命周期')
    await expect(page.getByTestId('document-delivery-review-panel')).toContainText('评论/版本')
    await expect(page.getByTestId('document-delivery-review-panel')).toContainText('交付包')
    await expect(page.getByTestId('document-delivery-review-panel')).toContainText('追溯')
    await expect(page.getByTestId('document-delivery-review-panel')).toContainText('协同动作')
    await expect(page.getByTestId('document-lifecycle-heading')).toBeVisible()
    await expect(page.getByTestId('document-tab-comments')).toBeVisible()
    await expect(page.getByTestId('document-tab-versions')).toBeVisible()
  })

  test('supports conversational authoring evidence for a downstream test document', async ({ page }) => {
    await gotoAppPage(page, '/projects/project-e2e-001/documents/generate?docType=test_case')

    await page.locator('#context').fill('基于 PRD 的出库复核功能生成测试用例，覆盖正常提交、异常拦截和发运确认。')
    await page.getByTestId('start-interactive-generation').click()
    await expect(page.getByTestId('interactive-generation-session')).toBeVisible({ timeout: 8000 })
    await expect(page).toHaveURL(/sessionId=gen-session-e2e-created/)
    await expect(page.getByTestId('authoring-session-cockpit')).toBeVisible()
    await expect(page.getByTestId('authoring-section-matrix')).toContainText('章节')
    await expect(page.getByTestId('authoring-section-detail')).toBeVisible()
    await expect(page.getByTestId('copy-generation-session-link')).toBeVisible()
    await expect(page.getByTestId('authoring-operation-queue')).toBeVisible()
    await expect(page.getByTestId('authoring-finalization-checklist')).toBeVisible()
    await expect(page.getByTestId('authoring-evidence-log')).toContainText('写入证据')
    await expect(page.getByTestId('authoring-skill-agent-plan')).toBeVisible()
    await expect(page.getByTestId('authoring-skill-agent-plan')).toContainText(/Skill\/Agent/)
    await expect(page.getByTestId('authoring-skill-agent-plan')).toContainText('推荐模板')
    await expect(page.getByTestId('authoring-skill-agent-plan')).toContainText('仅准备提示')
    await expect(page.getByTestId('authoring-section-evidence')).toContainText('段落/章节证据')
    await expect(page.getByTestId('authoring-section-evidence')).toContainText('质量评分')
    await page.getByTestId('apply-recommended-skill-prompt').first().click()
    await expect(page.getByTestId('authoring-message-input')).toHaveValue(/仅准备提示/)
    await expect(page.getByTestId('authoring-message-input')).toHaveValue(/Skill/)
    await page.getByTestId('execute-recommended-skill').first().click()
    await expect(page.getByTestId('authoring-skill-execution-result')).toContainText(/成功|鎴愬姛/, { timeout: 8000 })
    await expect(page.getByTestId('authoring-message-input')).toHaveValue(/Skill/)
    await expect(page.getByTestId('authoring-agent-run-summary')).toBeVisible()
    await page.getByTestId('use-current-section-question').click()
    await expect(page.getByTestId('authoring-message-input')).toHaveValue(/.+/)
    await page.getByTestId('authoring-section-focus').nth(1).click()
    await expect(page.getByTestId('authoring-section-detail')).toContainText('干系人')
    await page.getByTestId('focus-next-section').click()
    await expect(page.getByTestId('authoring-section-detail')).toContainText('流程')
    await page.getByTestId('focus-previous-section').click()
    await expect(page.getByTestId('authoring-section-detail')).toContainText('干系人')
    await page.getByTestId('use-focused-section-question').click()
    await expect(page.getByTestId('authoring-message-input')).toHaveValue(/.+/)

    await page.getByTestId('authoring-message-input').fill('测试范围覆盖出库复核、异常拦截和发运确认，优先级为高。')
    await page.getByTestId('authoring-answer-action').click()
    await expect(page.locator('body')).toContainText('写入与验证', { timeout: 8000 })
    await expect(page.locator('body')).toContainText('能力调用')
    await expect(page.locator('body')).toContainText('质量门禁')
    await expect(page.getByTestId('authoring-evidence-log')).toContainText('业务澄清')
    await expect(page.getByTestId('authoring-skill-agent-plan')).toContainText('活跃调用轨迹')
    await expect(page.getByTestId('authoring-skill-agent-plan')).toContainText('业务澄清')
    await expect(page.getByTestId('authoring-section-evidence')).toContainText('已确认事实')
    await page.getByTestId('use-pending-confirmation').first().click()
    await expect(page.getByTestId('authoring-message-input')).toHaveValue(/确认/)
    await page.getByTestId('use-operation-queue-item').first().click()
    await expect(page.getByTestId('authoring-message-input')).toHaveValue(/.+/)

    await page.getByTestId('authoring-message-input').fill('测试范围=>测试覆盖范围')
    await page.getByTestId('authoring-revise-action').click()
    await expect(page.locator('body')).toContainText('已验证', { timeout: 8000 })

    await page.getByTestId('authoring-confirm-action').click()
    await expect(page.locator('body')).toContainText(/步骤|steps|测试/)
  })
})
